<?php

// autoload_real.php @generated by Composer

class ComposerAutoloaderInit68a711549d470a09399b88d52a2e0dd2
{
    private static $loader;

    public static function loadClassLoader($class)
    {
        if ('DWT\LocalFonts\Vendor\Composer\Autoload\ClassLoader' === $class) {
            require __DIR__ . '/ClassLoader.php';
        }
    }

    /**
     * @return \DWT\LocalFonts\Vendor\Composer\Autoload\ClassLoader
     */
    public static function getLoader()
    {
        if (null !== self::$loader) {
            return self::$loader;
        }

        require __DIR__ . '/platform_check.php';

        spl_autoload_register(array('ComposerAutoloaderInit68a711549d470a09399b88d52a2e0dd2', 'loadClassLoader'), true, true);
        self::$loader = $loader = new \DWT\LocalFonts\Vendor\Composer\Autoload\ClassLoader(\dirname(__DIR__));
        spl_autoload_unregister(array('ComposerAutoloaderInit68a711549d470a09399b88d52a2e0dd2', 'loadClassLoader'));

        require __DIR__ . '/autoload_static.php';
        call_user_func(\DWT\LocalFonts\Vendor\Composer\Autoload\ComposerStaticInit68a711549d470a09399b88d52a2e0dd2::getInitializer($loader));

        $loader->setClassMapAuthoritative(true);
        $loader->register(true);

        return $loader;
    }
}
