<?php

// autoload_classmap.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'DWT\\LocalFonts\\Vendor\\Composer\\InstalledVersions' => $vendorDir . '/composer/InstalledVersions.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\AdobeFontMetrics' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/AdobeFontMetrics.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\BinaryStream' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/BinaryStream.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\EOT\\File' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/EOT/File.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\EOT\\Header' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/EOT/Header.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\EncodingMap' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/EncodingMap.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Exception\\FontNotFoundException' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Exception/FontNotFoundException.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Font' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Font.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\Outline' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Glyph/Outline.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineComponent' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineComponent.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineComposite' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineComposite.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineSimple' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineSimple.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Header' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Header.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\OpenType\\File' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/OpenType/File.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\OpenType\\TableDirectoryEntry' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/OpenType/TableDirectoryEntry.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\DirectoryEntry' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/DirectoryEntry.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Table' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Table.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\cmap' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/cmap.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\cvt' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/cvt.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\fpgm' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/fpgm.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\glyf' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/glyf.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\head' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/head.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\hhea' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/hhea.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\hmtx' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/hmtx.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\kern' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/kern.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\loca' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/loca.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\maxp' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/maxp.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\name' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/name.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\nameRecord' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/nameRecord.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\os2' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/os2.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\post' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/post.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\prep' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/Table/Type/prep.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\Collection' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/TrueType/Collection.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\File' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/TrueType/File.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\Header' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/TrueType/Header.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\TableDirectoryEntry' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/TrueType/TableDirectoryEntry.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\File' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/WOFF/File.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\Header' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/WOFF/Header.php',
    'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\TableDirectoryEntry' => $vendorDir . '/dompdf/php-font-lib/src/FontLib/WOFF/TableDirectoryEntry.php',
);
