<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(__DIR__);
$baseDir = dirname($vendorDir);

return array(
    'DWT\\LocalFonts\\Vendor\\FontLib\\' => array($vendorDir . '/dompdf/php-font-lib/src/FontLib'),
);
