<?php

// autoload_static.php @generated by Composer

namespace DWT\LocalFonts\Vendor\Composer\Autoload;

class ComposerStaticInit68a711549d470a09399b88d52a2e0dd2
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'DWT\\LocalFonts\\Vendor\\FontLib\\' => 30,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'DWT\\LocalFonts\\Vendor\\FontLib\\' => 
        array (
            0 => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib',
        ),
    );

    public static $classMap = array (
        'DWT\\LocalFonts\\Vendor\\Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\AdobeFontMetrics' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/AdobeFontMetrics.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\BinaryStream' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/BinaryStream.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\EOT\\File' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/EOT/File.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\EOT\\Header' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/EOT/Header.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\EncodingMap' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/EncodingMap.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Exception\\FontNotFoundException' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Exception/FontNotFoundException.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Font' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Font.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\Outline' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Glyph/Outline.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineComponent' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineComponent.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineComposite' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineComposite.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Glyph\\OutlineSimple' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Glyph/OutlineSimple.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Header' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Header.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\OpenType\\File' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/OpenType/File.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\OpenType\\TableDirectoryEntry' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/OpenType/TableDirectoryEntry.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\DirectoryEntry' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/DirectoryEntry.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Table' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Table.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\cmap' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/cmap.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\cvt' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/cvt.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\fpgm' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/fpgm.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\glyf' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/glyf.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\head' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/head.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\hhea' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/hhea.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\hmtx' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/hmtx.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\kern' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/kern.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\loca' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/loca.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\maxp' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/maxp.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\name' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/name.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\nameRecord' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/nameRecord.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\os2' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/os2.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\post' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/post.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\Table\\Type\\prep' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/Table/Type/prep.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\Collection' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/TrueType/Collection.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\File' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/TrueType/File.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\Header' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/TrueType/Header.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\TrueType\\TableDirectoryEntry' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/TrueType/TableDirectoryEntry.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\File' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/WOFF/File.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\Header' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/WOFF/Header.php',
        'DWT\\LocalFonts\\Vendor\\FontLib\\WOFF\\TableDirectoryEntry' => __DIR__ . '/..' . '/dompdf/php-font-lib/src/FontLib/WOFF/TableDirectoryEntry.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit68a711549d470a09399b88d52a2e0dd2::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit68a711549d470a09399b88d52a2e0dd2::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit68a711549d470a09399b88d52a2e0dd2::$classMap;

        }, null, ClassLoader::class);
    }
}
